### ISSUE TITLE
MAJ T411

### ISSUE THREAD

**Issue by jbarbin** [MartialGeek/t411-api-client#1]
URL of T411 api has changed recently : api.t411.in

Thanks a lot for this interface

**Comment by MartialGeek** [comment]
Oops sorry, I did not receive any notification for your issue!

The URL is not hard coded, since you must build a Guzzle client with the URL of your choice.
Or maybe you talk about the README?

**Comment by MartialGeek** [comment]
I have updated the URL of the API in the README.

**Comment by gilbert1995** [comment]
Now it api.t411.li :P
