### ISSUE TITLE
Missing parameter on documentation example

### ISSUE THREAD

**Issue by amiceli** [MartialGeek/t411-api-client#2]
There is a missing paramater in documentation example : 

    $client = new \Martial\T411\Api\Client($httpClient, $dataTransformer, $fs, $config);

Must be

    $client = new \Martial\T411\Api\Client($httpClient, $dataTransformer, $fs, $queryFactory, $config);

Thanks for your work

**Comment by MartialGeek** [comment]
Fixed, thank you for reporting this issue ;)
