### ISSUE TITLE
Compatibility with Laravel 5.3

### ISSUE THREAD

**Issue by gilbert1995** [MartialGeek/t411-api-client#3]
Hello, can your library be updated to be compatible with: "symfony / http-foundation": "3.1. *"

In order to make it compatible with Laravel 5.3

Thanks

**Comment by MartialGeek** [comment]
Hello

I just pushed a dev branch for that. Can you temporary modify your composer.json to test if the upgrade does not break your app please ?

martial/t411-api-client: "dev-upgrade-sf-deps"

**Comment by gilbert1995** [comment]
Hello,
I have successfully made a search request with the API.

I have successfully run your unit test with the new version of http-foundation.

Your unit test need a little update I have some warning:

> There were 12 warnings:

> 
> 1) Martial\T411\Api\Tests\ClientTest::testAuthenticateShouldReturnATokenInCaseOfSuccess
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 2) Martial\T411\Api\Tests\ClientTest::testAuthenticateShouldThrowAnExceptionWhenTheUserDoesNotExist
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 3) Martial\T411\Api\Tests\ClientTest::testAuthenticateShouldThrowAnExceptionOnNotConfirmedAccount
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 4) Martial\T411\Api\Tests\ClientTest::testAuthenticateShouldThrowAnExceptionWhenTheAuthorizationLimitIsReached
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 5) Martial\T411\Api\Tests\ClientTest::testAuthenticateShouldThrowAnExceptionWhenTheAccountIsDisabled
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 6) Martial\T411\Api\Tests\ClientTest::testAuthenticateShouldThrowAnExceptionWhenTheAccountIsDisabledByAnAdmin
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 7) Martial\T411\Api\Tests\ClientTest::testAuthenticateShouldThrowAnExceptionWhenTheAccountIsDisabledBecauseOfCheats
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 8) Martial\T411\Api\Tests\ClientTest::testAuthenticateShouldThrowAnExceptionWhenThePasswordIsWrong
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 9) Martial\T411\Api\Tests\ClientTest::testAuthenticateShouldTrowAnExceptionOnUnknownError
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 10) Martial\T411\Api\Tests\ClientTest::testCategoriesShouldReturnAListOfCategories
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 11) Martial\T411\Api\Tests\ClientTest::testSearchShouldReturnATorrentSearchResultInterface
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
> 
> 12) Martial\T411\Api\Tests\ClientTest::testDownloadShouldReturnAFile
> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
>

Thanks for your library and help ;)

**Comment by MartialGeek** [comment]
These warnings are thrown because you are using your own PHPUnit. If you run the test suite with ./vendor/bin/phpunit, you should not have the deprecated calls.
However, you are right about using an old version of PHPUnit is bad, I will make an update for that in a forthcoming version ;)

**Comment by gilbert1995** [comment]
I use "phpunit/phpunit": "~5.0" ;)
