### ISSUE TITLE
Guzzle update

### ISSUE THREAD

**Issue by gilbert1995** [MartialGeek/t411-api-client#5]
Hello :),
Can you made an update tu use last Guzzle.

I have an other API library use:
"guzzlehttp/guzzle": "^6.1"

Thanks a lot for your time and help

**Comment by MartialGeek** [comment]
Hello

I think that it is a harder work than upgrading the Symfony components. The developer of Guzzle broke the BC with the version 6. Anyway, I have to do it because I will have the same problem very soon.

I will try to fix it the next WE ;)

**Comment by MartialGeek** [comment]
Finally I just upgraded the Guzzle version of my library (I'm sick today so I'm at home!), and also PHPUnit.
You can test by changing the version in your composer.json to "dev-guzzle-update". It should be completely transparent for you. If you validate I will merge this ASAP and tag a new minor release.

**Comment by gilbert1995** [comment]
Nice thk for all :+1:

**Comment by gilbert1995** [comment]
I found a little bug
https://github.com/MartialGeek/t411-api-client/compare/guzzle-update#diff-04c6e90faac2675aa89e2176d2eec7d8R21

The name of parameter "base_url" has change to "base_uri"

http://docs.guzzlephp.org/en/latest/request-options.html

The search works well for me and test for phpunit to :)

**Comment by MartialGeek** [comment]
Thank you, I fixed the README.
t411 often changes its URL!

I merged the code in the master and published a new minor release, you can run a composer update.

P.S: I suppose that you are French if you are a t411 user, so don't hesitate to write in French in this repository ;)

Bonne journée !

**Comment by gilbert1995** [comment]
Avoir sue que vous parliez français, je suis québécois et je maîtrise beaucoup plus le français ^^

**Comment by MartialGeek** [comment]
Moi je ne parle qu'un anglais technique ! Donc ça m'arrange aussi d'écrire en français.
En tout cas n'hésitez pas si vous avez d'autres demandes, ça me fait plaisir ;)
