### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by gilbert1995** [MartialGeek/t411-api-client#9]
Salut dans le readme il y a une coquille 

```php
$result = $client->search($token, [
    'terms' => 'ubuntu 14.04',
    'category_id' => 42,
    'offset' => 0,
    'limit' => 20
]);
```

Ce n'est plus "category_id" c'est rendu "cid" :)

**Comment by MartialGeek** [comment]
Salut

J'attends bien un paramètre "category_id" :
https://github.com/MartialGeek/t411-api-client/blob/master/src/Search/QueryFactory.php#L22

qui se transforme en paramètre GET "cid" :
https://github.com/MartialGeek/t411-api-client/blob/master/src/Search/Query.php#L38

Je trouvais que "cid" était naze comme nom, pas claire ;)

**Comment by gilbert1995** [comment]
Autant pour moi :P
